env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - google
parserOptions:
  ecmaVersion: latest
rules: {
  "object-curly-spacing": [2, "always"],
  "arrow-parens": [2, "as-needed", { "requireForBlockBody": true }],
  "max-len": ["warn", { "code": 150, "ignoreComments": true }],
  "indent": ["error", 2],
  "require-jsdoc" : 0,
  "prefer-const": ["error", {
      "destructuring": "any",
      "ignoreReadBeforeAssign": false
    }
  ]
}
